name: Cowsay Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t cowsay
    - name: check Docker image
      run: docker images
    - name: run Docker image
      run: docker run cowsay ILoveDevops
